# Digital Ocean App Platform Configuration
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: lauta-landing

services:
  - name: web
    github:
      repo: 20delta/lauta-landing
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    run_command: gunicorn app:app --bind 0.0.0.0:8080 --workers 2
    envs:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET

